import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/a9e7b27a0c5e986a22416d79e2e9dba9.jpg',
    title: 'Advanced API Design and Development with Python, Golang, and Rust',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
    website: 'https://my.workee.net/shnartho',
  },
  {
    id: 2,
    cover: '/images/courses/alvaro-reyes-qWwpHwip31M-unsplash.jpg',
    title: 'Mastering ETL Automation with Python',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
    website: 'https://my.workee.net/shnartho',
  },
  {
    id: 3,
    cover: '/images/courses/christopher-gower-m_HRfLhgABo-unsplash.jpg',
    title: 'Database Administration Essentials for Improved Performance and Security',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
    website: 'https://my.workee.net/shnartho',
  },
  {
    id: 4,
    cover: '/images/courses/true-agency-o4UhdLv5jbQ-unsplash.jpg',
    title: 'Data Analysis for Informed Decision-Making',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
    website: 'https://my.workee.net/shnartho',
  },
  {
    id: 5,
    cover: '/images/courses/stillness-inmotion-Jh6aQX-25Uo-unsplash.jpg',
    title: 'DevOps Practices Demystified with Docker, Kubernetes, CI/CD, Ansible, and Git',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
    website: 'https://my.workee.net/shnartho',
  },
  {
    id: 6,
    cover: '/images/courses/stillness-inmotion-YSCCnRGrD-4-unsplash.jpg',
    title: 'Cloud Infrastructure Management on GCP and AWS',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
    website: 'https://my.workee.net/shnartho',
  },
  {
    id: 7,
    cover: '/images/courses/grovemade-RvPDe41lYBA-unsplash.jpg',
    title: 'Monitoring Solutions and Troubleshooting for Seamless System Functionality',
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Beginner',
    website: 'https://my.workee.net/shnartho',
  },
];

